### ISSUE TITLE
Does GetAccounts method in client directory get all account?

### ISSUE THREAD

**Issue by imnisen** [bonedaddy/go-compound#4]
https://github.com/bonedaddy/go-compound/blob/a5fb6a8e382418b2cb4d2b596ee73a138ee61e27/client/utils.go#L134

It seems that requests all accounts don't specify `page_size ` and `page_number` params. Does it fetch all accounts actually?

**Comment by bonedaddy** [comment]
~It's been awhile since I've used this code so I can't quite remember.~ It returns a default of 10 accounts

**Comment by bonedaddy** [comment]
As of [this commit](https://github.com/bonedaddy/go-compound/commit/16a99790e3aa1bf62d96ff7384f6a6cef7e3bb1d) you can specify the page number and page size arguments. Going to close this as the issue should be resolved. Feel free to re-open, or create a new issue if there are any problems.
